manifest:
  remotes:
    # - name: zmkfirmware
    #   url-base: https://github.com/zmkfirmware
    - name: lazerwalker
      url-base: https://github.com/lazerwalker
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: lazerwalker
      revision: multiple-features
      import: app/west.yml
  self:
    path: config
